#数据源设置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learning?useUnicode=true&characterEncoding=UTF-8
    username: user
    password: mysql
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      #配置获取连接等待超时的时间
      max-wait: 60000
      # 校验
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
  #jpa相关配置
  # 显示sql 但不会显示具体的操作值 可以替换成log4jdbc
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
